//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorZdraw.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalAddressMAQC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LegalAddressMAQC()
        {
            this.ManufacturerAndQualityControl = new HashSet<ManufacturerAndQualityControl>();
        }
    
        public int IdLegalAddressMAQC { get; set; }
        public int IdCity { get; set; }
        public int IdStreet { get; set; }
        public string HouseNumber { get; set; }
        public string Building { get; set; }
    
        public virtual City City { get; set; }
        public virtual Street Street { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturerAndQualityControl> ManufacturerAndQualityControl { get; set; }
    }
}
