//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorZdraw.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manufacturer()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int IdManufacturer { get; set; }
        public int IdManufacturerAndQualityControl { get; set; }
        public Nullable<int> IdPacker { get; set; }
        public int IdOrganizationAcceptingClaims { get; set; }
    
        public virtual ManufacturerAndQualityControl ManufacturerAndQualityControl { get; set; }
        public virtual OrganizationAcceptingClaims OrganizationAcceptingClaims { get; set; }
        public virtual Packer Packer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
