//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorZdraw.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public int IdProduct { get; set; }
        public System.DateTime DateOrder { get; set; }
        public int QuantityOrder { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Priceall { get; set; }
        public int IdSuppliers { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
