//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorZdraw.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
            this.Sell = new HashSet<Sell>();
        }
    
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public string Composition { get; set; }
        public Nullable<int> IdСategory { get; set; }
        public string ReleaseForm { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public Nullable<int> IdSuppliers { get; set; }
        public string DosageForm { get; set; }
        public string Indications { get; set; }
        public string Contraindications { get; set; }
        public string MethodOfAdministrationAndDosage { get; set; }
        public string SideEffects { get; set; }
        public string Overdose { get; set; }
        public string DrugInteraction { get; set; }
        public string SpecialInstructions { get; set; }
        public string StorageConditions { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> IdRecipe { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sell> Sell { get; set; }
    }
}
