//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorZdraw.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int IdSell { get; set; }
        public int IdProductSell { get; set; }
        public int IdTypesell { get; set; }
        public int QuantitySell { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TypeSell TypeSell { get; set; }
    }
}
